service: s3-product-feed

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  environment:
    FEED_DELIMITER: ${self:custom.config.feedDelimiter}
    OUTPUT_BUCKET: ${self:custom.app-name}-${self:service}-${self:custom.config.stage}-${self:custom.config.outputBucket}
    CONFIG_BUCKET: ${self:custom.app-name}-${self:service}-${self:custom.config.stage}-${self:custom.config.configBucket}

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  
custom:
  config: ${file(config.json)}
  app-name: ${self:custom.config.appName}
  s3Buckets:
    SOURCES_BUCKET: ${self:custom.app-name}-${self:service}-${self:custom.config.stage}-sources-bucket

iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - s3:*
      Resource: 
        - "arn:aws:lambda:${self:custom.config.region}:*:function:*"
        - "arn:aws:ses:${self:custom.config.region}:*"
        - "arn:aws:ses:${self:custom.config.region}:*:identity/*"
        - "arn:aws:s3:::${self:custom.s3Buckets.SOURCES_BUCKET}/*"
        - "arn:aws:s3:::${self:custom.s3Buckets.SOURCES_BUCKET}"
        - "arn:aws:s3:::${self:environment.OUTPUT_BUCKET}/*"
        - "arn:aws:s3:::${self:environment.OUTPUT_BUCKET}"
        - "arn:aws:s3:::${self:environment.CONFIG_BUCKET}/*"
        - "arn:aws:s3:::${self:environment.CONFIG_BUCKET}"
        - "arn:aws:logs:${self:custom.config.region}:*:log-group:*"
        - "arn:aws:logs:${self:custom.config.region}:*:log-group:*:*:*"

functions:
  feed:
    handler: src/handlers/feed.run
    timeout: 900
    environment:
      FUNCTION_PREFIX: ${self:service}-${opt:stage, self:provider.stage}
    events:
      - s3:
          bucket: ${self:custom.s3Buckets.SOURCES_BUCKET}
          event: s3:ObjectCreated:*
          existing: true

resources:
  Resources:
    S3BucketFeedSources:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: '${self:custom.s3Buckets.SOURCES_BUCKET}'
    TransformLambdaPermissionS3:
      Type: 'AWS::Lambda::Permission'
      Properties:
        FunctionName:
          'Fn::GetAtt':
            - FeedLambdaFunction
            - Arn
        Principal: 's3.amazonaws.com'
        Action: 'lambda:InvokeFunction'
        SourceAccount:
          Ref: AWS::AccountId
        SourceArn: 'arn:aws:s3:::${self:custom.s3Buckets.SOURCES_BUCKET}'
    S3BucketFeedOutput:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: '${self:provider.environment.OUTPUT_BUCKET}'
    S3BucketConfiguration:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: '${self:provider.environment.CONFIG_BUCKET}'
    LambdaWritePermissionS3:
      Type: 'AWS::Lambda::Permission'
      Properties:
        FunctionName:
          'Fn::GetAtt':
            - FeedLambdaFunction
            - Arn
        Principal: 's3.amazonaws.com'
        Action: 'lambda:InvokeFunction'
        SourceAccount:
          Ref: AWS::AccountId
        SourceArn: 'arn:aws:s3:::${self:provider.environment.OUTPUT_BUCKET}'